### ISSUE TITLE
Contact me section işləmir.

### ISSUE THREAD

**Issue by DrMadWill** [RaviHamidov/RaviHamidov#1]
Sizdən bu spotify necə quraşdırdığınızı öyrənmək istəyirdim. Ancaq contact me dəki heç bir button işləmir. Ona görə buradan yazmalı oldum. Sizdən xaiş etsəm spotify necə etdiynizi mənə göstərə bilərsiz?

**Comment by ravi-hamidov** [comment]
Salammm Nofel 🖐 , Yess Tebii ki olar but , bidene Exam var onu verm eve
catan kimi Solve ederik 😁 , Maybe Foundation Reposundaki portfolio linkine
click etmisen sehv etmiremse ordaki portfolionun sadece Frontudu ona gore
gerek ReadMe ni modify edim ✌

27 Ara 2021 Pzt 15:01 tarihinde Nofel ***@***.***> şunu yazdı:

**Comment by DrMadWill** [comment]
No problem. Sadəcə bu token məsələsini anlamışam. təzə yenilikdi bu. ancaq catmir mənə

**Comment by DrMadWill** [comment]
## Ha bu arada nəsə dəstək lazımdırsa de bəlkə köməyimiz dəydi
